import { Header } from '@/components/header'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const gotham = localFont({
  src: [
    {
      path: '../../public/fonts/gotham-black.woff2',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../../public/fonts/gotham-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/gotham-book.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/gotham-light.woff2',
      weight: '300',
      style: 'normal',
    },
  ],
  variable: '--font-gotham',
  fallback: ['sans'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${gotham.className} font-sans`}>
        <Header />
        <main className="max-w-6xl mx-auto py-32 md:py-24 px-12">
          {children}
        </main>
      </body>
    </html>
  )
}
