import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const gotham = localFont({
  src: [
    {
      path: '../../public/fonts/gotham-black.woff2',
      weight: '900',
    },
    {
      path: '../../public/fonts/gotham-bold.woff2',
      weight: '700',
    },
    {
      path: '../../public/fonts/gotham-book.woff2',
      weight: '400',
    },
    {
      path: '../../public/fonts/gotham-light.woff2',
      weight: '300',
    },
  ],
  variable: '--font-gotham',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${gotham.className} font-sans`}>{children}</body>
    </html>
  )
}
